import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { assistant } from "@/components/font";
import Nav from '@/components/header/nav'
import Footer from "@/components/footer/footer";
// import { Providers } from "./provider";


const inter = Inter({ subsets: ["latin"] });




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
      <body className={assistant.className}>
        {/* <Providers> */}
          <div className="relative">
              <Nav />
              {/* <div className=" bg-red-500"> */}
                {children}
          {/* </div> */}
           <Footer/>
          </div>
        {/* </Providers> */}
      </body>
    </html>
  );
}
